export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_COLOR_PRIMARY = 'SET_COLOR_PRIMARY';
export const SET_COMPONENT_SIZE = 'SET_COMPONENT_SIZE';
export const RESET_THEME_STATE = "RESET_THEME_STATE"