const themeActions = {

  CHANGE_THEME: "CHANGE_THEME",
  SET_COLOR_PRIMARY: "SET_COLOR_PRIMARY",
  SET_COMPONENT_SIZE: "SET_COMPONENT_SIZE",
  RESET_THEME_STATE: "RESET_THEME_STATE"
} as const;

export default themeActions;