
export const SET_TABS = "SET_TABS"
export const REMOVE_TABS = "REMOVE_TABS"
export const DELETE_CURRENT_TAB = "DELETE_CURRENT_TAB"
export const DELETE_OTHER_TAB = "DELETE_OTHER_TAB"
export const DELETE_ALL_TAB = "DELETE_ALL_TAB"
export const SET_TABS_ACTIVE_KEY = "SET_TABS_ACTIVE_KEY"