const toHeaderAction = {
  SET_TABS: "SET_TABS",
  REMOVE_TABS: "REMOVE_TABS",
  SET_TABS_ACTIVE_KEY: "SET_TABS_ACTIVE_KEY",
  SET_PAGE_LAYOUT_ITEMS: "SET_PAGE_LAYOUT_ITEMS",
  SET_LAYOUT_MODE: "SET_LAYOUT_MODE",
  RESET_TOP_HEADER_STATE: "RESET_TOP_HEADER_STATE"
} as const;
export default toHeaderAction;