const GlobalActionTypes = {
  USER_SET_USER_TOKEN: "USER_SET_USER_TOKEN",
  USER_SET_USER_INFO: "USER_SET_USER_INFO",
  USER_RESET_USER: "USER_RESET_USER",
  UPDATE_COLLAPSE: "UPDATE_COLLAPSE",

} as const;
export default GlobalActionTypes
