name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to jsDelivr
        uses: chriscorchado/jsdelivr-action@v1.1
        with:
          files: dist/**
          dir: /
          endpoint: jsdelivr
          zone_id: ${{ secrets.REACT_ADMIN }}
          token: ${{ secrets.REACT_ADMIN }}
          fallback: '/index.html'
